export const radius = 100;
export const holdBarHeight = 25;
export const hitZone = window.innerWidth/2  ;
export const precision = 15;
export const hitRange = [hitZone - precision, hitZone + precision]
export const numOfTargets = 5;
export const arrowTypes = ['left', 'right', 'up', 'down']
export const timelineY = window.innerHeight - 100
export const iconScale = 2